export const SALT = 8;
export const SECRET =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0MzIwMDEiLCJuYW1lIjoiTUFOSCBEVUMgTkdVWUVOIiwiaWF0Ijo2MjgyMDIyfQ.2Fbhw7k7fOHt9Egtb44V0spxhsViNV8rjVtWIGyoU6g";
